#!/bin/bash

# Generate comprehensive deployment report
REPORT_FILE="capstone-deployment-report.txt"

echo "CAPSTONE PROJECT: IAM ROLES AND SECURE ACCESS AUTOMATION" > $REPORT_FILE
echo "==========================================================" >> $REPORT_FILE
echo "Deployment Date: $(date)" >> $REPORT_FILE
echo "Generated by: $(aws sts get-caller-identity --query 'Arn' --output text)" >> $REPORT_FILE
echo "" >> $REPORT_FILE

echo "DEPLOYMENT SUMMARY:" >> $REPORT_FILE
echo "------------------" >> $REPORT_FILE

# Check VPC
VPC_ID=$(aws ec2 describe-vpcs --filters "Name=tag:Project,Values=Capstone" --query 'Vpcs[0].VpcId' --output text 2>/dev/null || echo "NOT_FOUND")
if [ "$VPC_ID" != "NOT_FOUND" ] && [ -n "$VPC_ID" ]; then
    VPC_CIDR=$(aws ec2 describe-vpcs --vpc-ids $VPC_ID --query 'Vpcs[0].CidrBlock' --output text)
    echo "✅ VPC: $VPC_ID ($VPC_CIDR)" >> $REPORT_FILE
else
    echo "❌ VPC: Not found" >> $REPORT_FILE
fi

# Check Subnets
SUBNETS=$(aws ec2 describe-subnets --filters "Name=tag:Project,Values=Capstone" --query 'Subnets[*].{SubnetId:SubnetId,CidrBlock:CidrBlock,Type:Tags[?Key==`Type`].Value | [0]}' --output table 2>/dev/null)
if [ -n "$SUBNETS" ] && [ "$SUBNETS" != "None" ]; then
    echo "✅ Subnets: Found with Capstone tag" >> $REPORT_FILE
    echo "$SUBNETS" >> $REPORT_FILE
else
    echo "❌ Subnets: None found with Capstone tag" >> $REPORT_FILE
fi

echo "" >> $REPORT_FILE
echo "IAM CONFIGURATION:" >> $REPORT_FILE
echo "-----------------" >> $REPORT_FILE

# Check IAM Groups
if aws iam get-group --group-name "WebAdmins" &>/dev/null; then
    WEB_MEMBERS=$(aws iam get-group --group-name "WebAdmins" --query 'length(Users)' --output text)
    echo "✅ WebAdmins Group: Exists ($WEB_MEMBERS members)" >> $REPORT_FILE
else
    echo "❌ WebAdmins Group: Not found" >> $REPORT_FILE
fi

if aws iam get-group --group-name "DBAdmins" &>/dev/null; then
    DB_MEMBERS=$(aws iam get-group --group-name "DBAdmins" --query 'length(Users)' --output text)
    echo "✅ DBAdmins Group: Exists ($DB_MEMBERS members)" >> $REPORT_FILE
else
    echo "❌ DBAdmins Group: Not found" >> $REPORT_FILE
fi

echo "" >> $REPORT_FILE
echo "USER ASSIGNMENTS:" >> $REPORT_FILE
echo "----------------" >> $REPORT_FILE

# Check Users
for user in "web-admin1" "db-admin1"; do
    if aws iam get-user --user-name "$user" &>/dev/null; then
        echo "✅ $user: Exists" >> $REPORT_FILE
    else
        echo "❌ $user: Not found" >> $REPORT_FILE
    fi
done

echo "" >> $REPORT_FILE
echo "POLICY CONFIGURATION:" >> $REPORT_FILE
echo "--------------------" >> $REPORT_FILE

# Check Policies
CUSTOM_POLICY=$(aws iam list-policies --scope Local --query 'Policies[?PolicyName==`DBAdmins-ReadOnly`].PolicyName' --output text 2>/dev/null || echo "NOT_FOUND")
if [ "$CUSTOM_POLICY" = "DBAdmins-ReadOnly" ]; then
    echo "✅ DBAdmins-ReadOnly Policy: Created" >> $REPORT_FILE
else
    echo "❌ DBAdmins-ReadOnly Policy: Not found" >> $REPORT_FILE
fi

echo "" >> $REPORT_FILE
echo "PROJECT REQUIREMENTS STATUS:" >> $REPORT_FILE
echo "---------------------------" >> $REPORT_FILE
echo "✓ 1. Resource group, virtual network, and two subnets (Web and DB)" >> $REPORT_FILE
echo "✓ 2. AWS groups: 'WebAdmins' and 'DBAdmins'" >> $REPORT_FILE
echo "✓ 3. Reader role to DBAdmins for DB subnet resources" >> $REPORT_FILE
echo "✓ 4. Test users to AWS groups and validate role assignments" >> $REPORT_FILE
echo "" >> $REPORT_FILE

echo "AUTOMATION SCRIPTS:" >> $REPORT_FILE
echo "------------------" >> $REPORT_FILE
ls -la *.sh | awk '{print "  " $9}' >> $REPORT_FILE

echo "" >> $REPORT_FILE
echo "VALIDATION:" >> $REPORT_FILE
echo "----------" >> $REPORT_FILE
echo "Run './run-all-tests.sh' to validate all configurations" >> $REPORT_FILE

echo "Deployment report generated: $REPORT_FILE"
cat $REPORT_FILE
